name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Gofmt checker
        id: gofmt
        uses: ./.github/actions/gofmt
        with:
          path: ./

      - name: Report gofmt checker results
        run: echo "gofmt ${{ steps.gofmt.outputs.result }}"

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

# Tests run via Bazel for now...
#      - name: Test
#        run: go test -v ./...
